#pragma once

#define MARIO_ACCELERATION			0.0003f
#define MARIO_WALKING_SPEED_MIN		0.05f

#define MARIO_STATE_WALKING_LEFT		-2
#define MARIO_STATE_IDLE				-1
#define MARIO_STATE_WALKING_RIGHT		0
#define MARIO_STATE_MAX_SPEED			1
#define MARIO_STATE_JUMP				2
#define MARIO_STATE_BRAKE				3
#define MARIO_STATE_SITDOWN				4
#define MARIO_STATE_HOLD				5
#define MARIO_STATE_FLY					6
#define MARIO_STATE_KICK				7
#define MARIO_STATE_JUMP_RIGHT			8
#define MARIO_STATE_JUMP_LEFT			9
#define MARIO_STATE_JUMP_X				10
#define MARIO_STATE_TRANSFORM			11
#define MARIO_STATE_DIE					12
#define MARIO_STATE_READY_TO_HOLD		13
#define MARIO_STATE_TAIL_ATTACK			14

#define MARIO_GRAVITY				0.002f

//! LEVEL
#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_TAIL	3
#define	MARIO_LEVEL_FIRE	4

//! SMALL
#define MARIO_ANI_SMALL_IDLE_RIGHT			0
#define MARIO_ANI_SMALL_WALKING_RIGHT		1
#define MARIO_ANI_SMALL_WALKING_FAST_RIGHT	2
#define MARIO_ANI_SMALL_RUNNING_RIGHT		3
#define MARIO_ANI_SMALL_JUMPINGUP_RIGHT		4
#define MARIO_ANI_SMALL_JUMPINGDOWN_RIGHT	5
#define MARIO_ANI_SMALL_BRAKING_RIGHT		6

#define MARIO_ANI_SMALL_IDLE_LEFT			7
#define MARIO_ANI_SMALL_WALKING_LEFT		8
#define MARIO_ANI_SMALL_WALKING_FAST_LEFT	9
#define MARIO_ANI_SMALL_RUNNING_LEFT		10
#define MARIO_ANI_SMALL_JUMPINGUP_LEFT		11
#define MARIO_ANI_SMALL_JUMPINGDOWN_LEFT	12
#define MARIO_ANI_SMALL_BRAKING_LEFT		13